# Nix -> Pkl renderer for hk configuration.
#
# Turns a Nix attrset describing an hk.pkl into a Pkl source string that
# `amends` a local (store-path) copy of hk's Config.pkl schema, so evaluation
# is fully offline — no `package://` fetch — and works inside the nix build
# sandbox. This is the hk analogue of lefthook.nix's `builtins.toJSON`+jq step,
# except Pkl is not JSON so we need a small, hk-shaped pretty-printer.
{ lib }:

let
  inherit (builtins)
    isBool
    isInt
    isString
    isList
    isAttrs
    ;

  # Pkl string literals use JSON-like backslash escapes. Escape backslash and
  # quote first, then control characters (so their inserted backslashes are not
  # re-escaped). Note: hk template braces like `{{files}}` are literal in Pkl
  # (Pkl interpolation is `\(...)`, not `{{...}}`), so they need no escaping.
  escape =
    s: builtins.replaceStrings [ "\n" "\t" "\r" ] [ "\\n" "\\t" "\\r" ] (lib.escape [ "\\" "\"" ] s);

  indent = n: lib.concatStrings (lib.genList (_: "  ") n);

  # Keys whose values are Pkl `Mapping`s (rendered with `["key"]` entry syntax)
  # rather than plain object properties. This is the entire hk-specific bit of
  # knowledge the renderer needs.
  mappingKeys = [
    "hooks"
    "steps"
    "env"
  ];

  renderScalar =
    v:
    if isBool v then
      (if v then "true" else "false")
    else if isInt v then
      toString v
    else if isString v then
      "\"${escape v}\""
    else if isList v then
      "List(${lib.concatMapStringsSep ", " renderScalar v})"
    else
      throw "hk-nix: cannot render value of unsupported type: ${builtins.typeOf v}";

  # An object body: `name = value` for scalars, `name { ... }` for nested
  # objects, and `name { ["k"] ... }` for the known Mapping-valued keys.
  renderObject =
    depth: attrs:
    let
      pad = indent depth;
      renderEntry =
        name: value:
        if isAttrs value && builtins.elem name mappingKeys then
          "${pad}${name} {\n${renderMapping (depth + 1) value}\n${pad}}"
        else if isAttrs value then
          "${pad}${name} {\n${renderObject (depth + 1) value}\n${pad}}"
        else
          "${pad}${name} = ${renderScalar value}";
    in
    lib.concatStringsSep "\n" (lib.mapAttrsToList renderEntry attrs);

  # A Mapping body: `["key"] { ... }` for object values, `["key"] = value` for
  # scalar values (e.g. `env`).
  renderMapping =
    depth: attrs:
    let
      pad = indent depth;
      renderEntry =
        name: value:
        if isAttrs value then
          "${pad}[\"${escape name}\"] {\n${renderObject (depth + 1) value}\n${pad}}"
        else
          "${pad}[\"${escape name}\"] = ${renderScalar value}";
    in
    lib.concatStringsSep "\n" (lib.mapAttrsToList renderEntry attrs);
in
{
  # renderHkPkl { schemaPath, settings } -> Pkl source string.
  #   schemaPath: absolute path to hk's Config.pkl (a /nix/store path).
  #   settings:   the hk.pkl top-level as a Nix attrset, e.g. { hooks = { ... }; }.
  renderHkPkl =
    {
      schemaPath,
      settings,
    }:
    ''
      // This file is generated by hk-nix. Manual changes will be overwritten.
      amends "${toString schemaPath}"

    ''
    + (renderObject 0 settings)
    + "\n";
}
